[project]
name = "advanced_ai_project"
version = "1.0-dev"
dependencies = [
    "tqdm~=4.67.1",
    "optuna~=4.2.1",
    "torchinfo~=1.8.0",
]

[project.scripts]
"advanced_ai_project" = "advanced_ai_project.main:main"
