[project]
name = "advanced_ai_project"
version = "1.0-dev"
dependencies = [
    "torch~=2.7.0",
    "torchvision~=0.22.0",
    "tqdm~=4.67.1",
    "optuna~=4.3.0",
    "torchinfo~=1.8.0",
]

[project.scripts]
"advanced_ai_project" = "advanced_ai_project.cli:main"
